name: Feature Suggestion
description: Suggest an idea for this project
title: "[Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion
      description: What would you like to see added or changed?
      placeholder: Describe your idea here
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      description: How would this improve the project?
      placeholder: Explain the benefits
    validations:
      required: true